-- ============================================================
-- Sales & Stock ERP Mini
-- Database Schema
-- MariaDB / MySQL
-- ============================================================

CREATE DATABASE IF NOT EXISTS mini_sales_stock_erp
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE mini_sales_stock_erp;

-- ============================================================
-- Users (authentication)
-- ============================================================
-- Passwords are stored as bcrypt hashes generated by PHP's
-- password_hash()/password_verify(). Never store plain text.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,

    is_active TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE KEY uk_users_username (username)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Categories (product categorization)
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    name VARCHAR(100) NOT NULL,

    is_active TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE KEY uk_categories_name (name)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Products
-- ============================================================
-- Products are deactivated (is_active = 0), never physically deleted,
-- because they may be referenced by sales/inventory records.
-- category_id is nullable so a deleted category does not cascade-delete
-- its products; the application always assigns a valid category.

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL,

    category_id BIGINT UNSIGNED NULL,

    price DECIMAL(12,2) NOT NULL DEFAULT 0.00,

    is_active TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE KEY uk_products_code (code),

    KEY idx_products_category_id (category_id),
    KEY idx_products_is_active (is_active),

    CONSTRAINT fk_products_category_id FOREIGN KEY (category_id)
        REFERENCES categories (id)
        ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Seed data: default categories
-- ============================================================
-- INSERT IGNORE keeps re-runs of this script idempotent.

INSERT IGNORE INTO categories (name, is_active) VALUES
    ('General', 1),
    ('Food & Beverage', 1),
    ('Electronics', 1),
    ('Clothing', 1);

-- ============================================================
-- Seed data: sample products
-- ============================================================
-- Categories are resolved by name so the seed survives category
-- re-insertion with different IDs. Codes are unique, so INSERT IGNORE
-- keeps re-runs of this script idempotent. A few products are seeded
-- inactive to demonstrate the status badge and the Disable action.

INSERT IGNORE INTO products (name, code, category_id, price, is_active) VALUES
    -- Electronics
    ('Arduino Uno R3',                'PRD-0001', (SELECT id FROM categories WHERE name = 'Electronics'),  24.90,  1),
    ('USB-C Cable 2m',                'PRD-0002', (SELECT id FROM categories WHERE name = 'Electronics'),   9.50,  1),
    ('Wireless Mouse',                'PRD-0003', (SELECT id FROM categories WHERE name = 'Electronics'),  15.00,  1),
    ('Bluetooth Headphones',          'PRD-0004', (SELECT id FROM categories WHERE name = 'Electronics'),  49.99,  1),
    ('LED Monitor 24"',               'PRD-0005', (SELECT id FROM categories WHERE name = 'Electronics'), 129.00,  1),
    ('Mechanical Keyboard',           'PRD-0006', (SELECT id FROM categories WHERE name = 'Electronics'),  89.50,  1),
    ('HD Webcam',                     'PRD-0007', (SELECT id FROM categories WHERE name = 'Electronics'),  39.90,  1),
    ('Power Bank 10000mAh',           'PRD-0008', (SELECT id FROM categories WHERE name = 'Electronics'),  29.99,  1),
    ('Phone Case (Legacy Model)',     'PRD-0024', (SELECT id FROM categories WHERE name = 'Electronics'),   7.50,  0),

    -- Food & Beverage
    ('Espresso Beans 1kg',            'PRD-0009', (SELECT id FROM categories WHERE name = 'Food & Beverage'), 19.99, 1),
    ('Green Tea 100g',                'PRD-0010', (SELECT id FROM categories WHERE name = 'Food & Beverage'),  6.50, 1),
    ('Olive Oil 750ml',               'PRD-0011', (SELECT id FROM categories WHERE name = 'Food & Beverage'), 12.75, 1),
    ('Raw Honey 500g',                'PRD-0012', (SELECT id FROM categories WHERE name = 'Food & Beverage'),  8.99, 1),
    ('Granola 400g',                  'PRD-0013', (SELECT id FROM categories WHERE name = 'Food & Beverage'),  5.25, 1),
    ('Snack Mix (Discontinued)',      'PRD-0023', (SELECT id FROM categories WHERE name = 'Food & Beverage'),  3.75, 0),

    -- Clothing
    ('Cotton T-Shirt',                'PRD-0014', (SELECT id FROM categories WHERE name = 'Clothing'), 14.00, 1),
    ('Denim Jacket',                  'PRD-0015', (SELECT id FROM categories WHERE name = 'Clothing'), 59.90, 1),
    ('Wool Scarf',                    'PRD-0016', (SELECT id FROM categories WHERE name = 'Clothing'), 18.50, 1),
    ('Running Sneakers',              'PRD-0017', (SELECT id FROM categories WHERE name = 'Clothing'), 45.00, 1),

    -- General
    ('A5 Notebook',                   'PRD-0018', (SELECT id FROM categories WHERE name = 'General'),  4.50, 1),
    ('Ballpoint Pens (Pack of 10)',   'PRD-0019', (SELECT id FROM categories WHERE name = 'General'),  6.00, 1),
    ('LED Desk Lamp',                 'PRD-0020', (SELECT id FROM categories WHERE name = 'General'), 22.00, 1),
    ('Ergonomic Office Chair',        'PRD-0021', (SELECT id FROM categories WHERE name = 'General'), 89.00, 1),
    ('Paper Clips (Box)',             'PRD-0022', (SELECT id FROM categories WHERE name = 'General'),  2.20, 1);

-- ============================================================
-- Warehouses (inventory locations)
-- ============================================================

CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    name VARCHAR(100) NOT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE KEY uk_warehouses_name (name)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Warehouse stock (current quantity per warehouse/product)
-- ============================================================
-- One row per warehouse/product pair; quantity is the current on-hand
-- stock. No movements, batches, transfers or history are tracked.

CREATE TABLE IF NOT EXISTS warehouse_stock (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    warehouse_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,

    quantity INT UNSIGNED NOT NULL DEFAULT 0,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE KEY uk_warehouse_stock_pair (warehouse_id, product_id),

    KEY idx_warehouse_stock_product_id (product_id),

    CONSTRAINT fk_warehouse_stock_warehouse_id FOREIGN KEY (warehouse_id)
        REFERENCES warehouses (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_warehouse_stock_product_id FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Seed data: sample warehouses
-- ============================================================

INSERT IGNORE INTO warehouses (name) VALUES
    ('Main Warehouse'),
    ('Second Warehouse');

-- ============================================================
-- Seed data: sample warehouse stock
-- ============================================================
-- Warehouses are resolved by name and products by code so the seed
-- survives re-insertion with different IDs. The unique
-- (warehouse_id, product_id) pair keeps INSERT IGNORE idempotent.

INSERT IGNORE INTO warehouse_stock (warehouse_id, product_id, quantity) VALUES
    ((SELECT id FROM warehouses WHERE name = 'Main Warehouse'),   (SELECT id FROM products WHERE code = 'PRD-0001'), 25),
    ((SELECT id FROM warehouses WHERE name = 'Main Warehouse'),   (SELECT id FROM products WHERE code = 'PRD-0002'), 10),
    ((SELECT id FROM warehouses WHERE name = 'Main Warehouse'),   (SELECT id FROM products WHERE code = 'PRD-0003'),  8),
    ((SELECT id FROM warehouses WHERE name = 'Second Warehouse'), (SELECT id FROM products WHERE code = 'PRD-0001'),  8),
    ((SELECT id FROM warehouses WHERE name = 'Second Warehouse'), (SELECT id FROM products WHERE code = 'PRD-0004'),  5),
    ((SELECT id FROM warehouses WHERE name = 'Second Warehouse'), (SELECT id FROM products WHERE code = 'PRD-0009'), 12);

-- ============================================================
-- Customers
-- ============================================================
-- Intentionally minimal: only a name and an optional phone number.
-- No addresses, emails, groups, notes or other CRM-style fields.

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    name VARCHAR(150) NOT NULL,
    phone VARCHAR(30) NULL,

    PRIMARY KEY (id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
